// Full ISO 3166-1 country list with dial codes (244 countries).
// Dial codes: intl-tel-input v25.3.1
// Names: umpirsky/country-list (en + zh)
// Flag emoji: derived from ISO alpha-2 regional indicator letters
// Pinyin: pypinyin (used for sorting the Chinese page alphabetically by pinyin)

export interface CountryCodeEntry {
  iso: string;       // ISO 3166-1 alpha-2, e.g. "cn"
  dial: string;      // Dial code, e.g. "+86"
  name: string;      // English name, e.g. "China"
  nameZh: string;    // Chinese name, e.g. "中国"
  pinyin: string;    // Pinyin of nameZh, space-separated, e.g. "zhong guo"
  flag: string;      // Unicode flag emoji, e.g. "🇨🇳"
}

export const COUNTRY_CODES: CountryCodeEntry[] = [
  { iso: 'af', dial: '+93', name: 'Afghanistan', nameZh: '阿富汗', pinyin: 'a fu han', flag: '🇦🇫' },
  { iso: 'ax', dial: '+358', name: 'Åland Islands', nameZh: '奥兰群岛', pinyin: 'ao lan qun dao', flag: '🇦🇽' },
  { iso: 'al', dial: '+355', name: 'Albania', nameZh: '阿尔巴尼亚', pinyin: 'a er ba ni ya', flag: '🇦🇱' },
  { iso: 'dz', dial: '+213', name: 'Algeria', nameZh: '阿尔及利亚', pinyin: 'a er ji li ya', flag: '🇩🇿' },
  { iso: 'as', dial: '+1', name: 'American Samoa', nameZh: '美属萨摩亚', pinyin: 'mei shu sa mo ya', flag: '🇦🇸' },
  { iso: 'ad', dial: '+376', name: 'Andorra', nameZh: '安道尔', pinyin: 'an dao er', flag: '🇦🇩' },
  { iso: 'ao', dial: '+244', name: 'Angola', nameZh: '安哥拉', pinyin: 'an ge la', flag: '🇦🇴' },
  { iso: 'ai', dial: '+1', name: 'Anguilla', nameZh: '安圭拉', pinyin: 'an gui la', flag: '🇦🇮' },
  { iso: 'ag', dial: '+1', name: 'Antigua & Barbuda', nameZh: '安提瓜和巴布达', pinyin: 'an ti gua he ba bu da', flag: '🇦🇬' },
  { iso: 'ar', dial: '+54', name: 'Argentina', nameZh: '阿根廷', pinyin: 'a gen ting', flag: '🇦🇷' },
  { iso: 'am', dial: '+374', name: 'Armenia', nameZh: '亚美尼亚', pinyin: 'ya mei ni ya', flag: '🇦🇲' },
  { iso: 'aw', dial: '+297', name: 'Aruba', nameZh: '阿鲁巴', pinyin: 'a lu ba', flag: '🇦🇼' },
  { iso: 'ac', dial: '+247', name: 'Ascension Island', nameZh: '阿森松岛', pinyin: 'a sen song dao', flag: '🇦🇨' },
  { iso: 'au', dial: '+61', name: 'Australia', nameZh: '澳大利亚', pinyin: 'ao da li ya', flag: '🇦🇺' },
  { iso: 'at', dial: '+43', name: 'Austria', nameZh: '奥地利', pinyin: 'ao di li', flag: '🇦🇹' },
  { iso: 'az', dial: '+994', name: 'Azerbaijan', nameZh: '阿塞拜疆', pinyin: 'a sai bai jiang', flag: '🇦🇿' },
  { iso: 'bs', dial: '+1', name: 'Bahamas', nameZh: '巴哈马', pinyin: 'ba ha ma', flag: '🇧🇸' },
  { iso: 'bh', dial: '+973', name: 'Bahrain', nameZh: '巴林', pinyin: 'ba lin', flag: '🇧🇭' },
  { iso: 'bd', dial: '+880', name: 'Bangladesh', nameZh: '孟加拉国', pinyin: 'meng jia la guo', flag: '🇧🇩' },
  { iso: 'bb', dial: '+1', name: 'Barbados', nameZh: '巴巴多斯', pinyin: 'ba ba duo si', flag: '🇧🇧' },
  { iso: 'by', dial: '+375', name: 'Belarus', nameZh: '白俄罗斯', pinyin: 'bai e luo si', flag: '🇧🇾' },
  { iso: 'be', dial: '+32', name: 'Belgium', nameZh: '比利时', pinyin: 'bi li shi', flag: '🇧🇪' },
  { iso: 'bz', dial: '+501', name: 'Belize', nameZh: '伯利兹', pinyin: 'bo li zi', flag: '🇧🇿' },
  { iso: 'bj', dial: '+229', name: 'Benin', nameZh: '贝宁', pinyin: 'bei ning', flag: '🇧🇯' },
  { iso: 'bm', dial: '+1', name: 'Bermuda', nameZh: '百慕大', pinyin: 'bai mu da', flag: '🇧🇲' },
  { iso: 'bt', dial: '+975', name: 'Bhutan', nameZh: '不丹', pinyin: 'bu dan', flag: '🇧🇹' },
  { iso: 'bo', dial: '+591', name: 'Bolivia', nameZh: '玻利维亚', pinyin: 'bo li wei ya', flag: '🇧🇴' },
  { iso: 'ba', dial: '+387', name: 'Bosnia & Herzegovina', nameZh: '波斯尼亚和黑塞哥维那', pinyin: 'bo si ni ya he hei sai ge wei na', flag: '🇧🇦' },
  { iso: 'bw', dial: '+267', name: 'Botswana', nameZh: '博茨瓦纳', pinyin: 'bo ci wa na', flag: '🇧🇼' },
  { iso: 'br', dial: '+55', name: 'Brazil', nameZh: '巴西', pinyin: 'ba xi', flag: '🇧🇷' },
  { iso: 'io', dial: '+246', name: 'British Indian Ocean Territory', nameZh: '英属印度洋领地', pinyin: 'ying shu yin du yang ling di', flag: '🇮🇴' },
  { iso: 'vg', dial: '+1', name: 'British Virgin Islands', nameZh: '英属维尔京群岛', pinyin: 'ying shu wei er jing qun dao', flag: '🇻🇬' },
  { iso: 'bn', dial: '+673', name: 'Brunei', nameZh: '文莱', pinyin: 'wen lai', flag: '🇧🇳' },
  { iso: 'bg', dial: '+359', name: 'Bulgaria', nameZh: '保加利亚', pinyin: 'bao jia li ya', flag: '🇧🇬' },
  { iso: 'bf', dial: '+226', name: 'Burkina Faso', nameZh: '布基纳法索', pinyin: 'bu ji na fa suo', flag: '🇧🇫' },
  { iso: 'bi', dial: '+257', name: 'Burundi', nameZh: '布隆迪', pinyin: 'bu long di', flag: '🇧🇮' },
  { iso: 'kh', dial: '+855', name: 'Cambodia', nameZh: '柬埔寨', pinyin: 'jian pu zhai', flag: '🇰🇭' },
  { iso: 'cm', dial: '+237', name: 'Cameroon', nameZh: '喀麦隆', pinyin: 'ka mai long', flag: '🇨🇲' },
  { iso: 'ca', dial: '+1', name: 'Canada', nameZh: '加拿大', pinyin: 'jia na da', flag: '🇨🇦' },
  { iso: 'cv', dial: '+238', name: 'Cape Verde', nameZh: '佛得角', pinyin: 'fu de jiao', flag: '🇨🇻' },
  { iso: 'bq', dial: '+599', name: 'Caribbean Netherlands', nameZh: '荷属加勒比区', pinyin: 'he shu jia lei bi qu', flag: '🇧🇶' },
  { iso: 'ky', dial: '+1', name: 'Cayman Islands', nameZh: '开曼群岛', pinyin: 'kai man qun dao', flag: '🇰🇾' },
  { iso: 'cf', dial: '+236', name: 'Central African Republic', nameZh: '中非共和国', pinyin: 'zhong fei gong he guo', flag: '🇨🇫' },
  { iso: 'td', dial: '+235', name: 'Chad', nameZh: '乍得', pinyin: 'zha de', flag: '🇹🇩' },
  { iso: 'cl', dial: '+56', name: 'Chile', nameZh: '智利', pinyin: 'zhi li', flag: '🇨🇱' },
  { iso: 'cn', dial: '+86', name: 'China', nameZh: '中国', pinyin: 'zhong guo', flag: '🇨🇳' },
  { iso: 'cx', dial: '+61', name: 'Christmas Island', nameZh: '圣诞岛', pinyin: 'sheng dan dao', flag: '🇨🇽' },
  { iso: 'cc', dial: '+61', name: 'Cocos (Keeling) Islands', nameZh: '科科斯（基林）群岛', pinyin: 'ke ke si （ ji lin ） qun dao', flag: '🇨🇨' },
  { iso: 'co', dial: '+57', name: 'Colombia', nameZh: '哥伦比亚', pinyin: 'ge lun bi ya', flag: '🇨🇴' },
  { iso: 'km', dial: '+269', name: 'Comoros', nameZh: '科摩罗', pinyin: 'ke mo luo', flag: '🇰🇲' },
  { iso: 'cg', dial: '+242', name: 'Congo - Brazzaville', nameZh: '刚果（布）', pinyin: 'gang guo （ bu ）', flag: '🇨🇬' },
  { iso: 'cd', dial: '+243', name: 'Congo - Kinshasa', nameZh: '刚果（金）', pinyin: 'gang guo （ jin ）', flag: '🇨🇩' },
  { iso: 'ck', dial: '+682', name: 'Cook Islands', nameZh: '库克群岛', pinyin: 'ku ke qun dao', flag: '🇨🇰' },
  { iso: 'cr', dial: '+506', name: 'Costa Rica', nameZh: '哥斯达黎加', pinyin: 'ge si da li jia', flag: '🇨🇷' },
  { iso: 'ci', dial: '+225', name: 'Côte d’Ivoire', nameZh: '科特迪瓦', pinyin: 'ke te di wa', flag: '🇨🇮' },
  { iso: 'hr', dial: '+385', name: 'Croatia', nameZh: '克罗地亚', pinyin: 'ke luo di ya', flag: '🇭🇷' },
  { iso: 'cu', dial: '+53', name: 'Cuba', nameZh: '古巴', pinyin: 'gu ba', flag: '🇨🇺' },
  { iso: 'cw', dial: '+599', name: 'Curaçao', nameZh: '库拉索', pinyin: 'ku la suo', flag: '🇨🇼' },
  { iso: 'cy', dial: '+357', name: 'Cyprus', nameZh: '塞浦路斯', pinyin: 'sai pu lu si', flag: '🇨🇾' },
  { iso: 'cz', dial: '+420', name: 'Czechia', nameZh: '捷克', pinyin: 'jie ke', flag: '🇨🇿' },
  { iso: 'dk', dial: '+45', name: 'Denmark', nameZh: '丹麦', pinyin: 'dan mai', flag: '🇩🇰' },
  { iso: 'dj', dial: '+253', name: 'Djibouti', nameZh: '吉布提', pinyin: 'ji bu ti', flag: '🇩🇯' },
  { iso: 'dm', dial: '+1', name: 'Dominica', nameZh: '多米尼克', pinyin: 'duo mi ni ke', flag: '🇩🇲' },
  { iso: 'do', dial: '+1', name: 'Dominican Republic', nameZh: '多米尼加共和国', pinyin: 'duo mi ni jia gong he guo', flag: '🇩🇴' },
  { iso: 'ec', dial: '+593', name: 'Ecuador', nameZh: '厄瓜多尔', pinyin: 'e gua duo er', flag: '🇪🇨' },
  { iso: 'eg', dial: '+20', name: 'Egypt', nameZh: '埃及', pinyin: 'ai ji', flag: '🇪🇬' },
  { iso: 'sv', dial: '+503', name: 'El Salvador', nameZh: '萨尔瓦多', pinyin: 'sa er wa duo', flag: '🇸🇻' },
  { iso: 'gq', dial: '+240', name: 'Equatorial Guinea', nameZh: '赤道几内亚', pinyin: 'chi dao ji nei ya', flag: '🇬🇶' },
  { iso: 'er', dial: '+291', name: 'Eritrea', nameZh: '厄立特里亚', pinyin: 'e li te li ya', flag: '🇪🇷' },
  { iso: 'ee', dial: '+372', name: 'Estonia', nameZh: '爱沙尼亚', pinyin: 'ai sha ni ya', flag: '🇪🇪' },
  { iso: 'sz', dial: '+268', name: 'Eswatini', nameZh: '斯威士兰', pinyin: 'si wei shi lan', flag: '🇸🇿' },
  { iso: 'et', dial: '+251', name: 'Ethiopia', nameZh: '埃塞俄比亚', pinyin: 'ai sai e bi ya', flag: '🇪🇹' },
  { iso: 'fk', dial: '+500', name: 'Falkland Islands', nameZh: '福克兰群岛', pinyin: 'fu ke lan qun dao', flag: '🇫🇰' },
  { iso: 'fo', dial: '+298', name: 'Faroe Islands', nameZh: '法罗群岛', pinyin: 'fa luo qun dao', flag: '🇫🇴' },
  { iso: 'fj', dial: '+679', name: 'Fiji', nameZh: '斐济', pinyin: 'fei ji', flag: '🇫🇯' },
  { iso: 'fi', dial: '+358', name: 'Finland', nameZh: '芬兰', pinyin: 'fen lan', flag: '🇫🇮' },
  { iso: 'fr', dial: '+33', name: 'France', nameZh: '法国', pinyin: 'fa guo', flag: '🇫🇷' },
  { iso: 'gf', dial: '+594', name: 'French Guiana', nameZh: '法属圭亚那', pinyin: 'fa shu gui ya na', flag: '🇬🇫' },
  { iso: 'pf', dial: '+689', name: 'French Polynesia', nameZh: '法属波利尼西亚', pinyin: 'fa shu bo li ni xi ya', flag: '🇵🇫' },
  { iso: 'ga', dial: '+241', name: 'Gabon', nameZh: '加蓬', pinyin: 'jia peng', flag: '🇬🇦' },
  { iso: 'gm', dial: '+220', name: 'Gambia', nameZh: '冈比亚', pinyin: 'gang bi ya', flag: '🇬🇲' },
  { iso: 'ge', dial: '+995', name: 'Georgia', nameZh: '格鲁吉亚', pinyin: 'ge lu ji ya', flag: '🇬🇪' },
  { iso: 'de', dial: '+49', name: 'Germany', nameZh: '德国', pinyin: 'de guo', flag: '🇩🇪' },
  { iso: 'gh', dial: '+233', name: 'Ghana', nameZh: '加纳', pinyin: 'jia na', flag: '🇬🇭' },
  { iso: 'gi', dial: '+350', name: 'Gibraltar', nameZh: '直布罗陀', pinyin: 'zhi bu luo tuo', flag: '🇬🇮' },
  { iso: 'gr', dial: '+30', name: 'Greece', nameZh: '希腊', pinyin: 'xi la', flag: '🇬🇷' },
  { iso: 'gl', dial: '+299', name: 'Greenland', nameZh: '格陵兰', pinyin: 'ge ling lan', flag: '🇬🇱' },
  { iso: 'gd', dial: '+1', name: 'Grenada', nameZh: '格林纳达', pinyin: 'ge lin na da', flag: '🇬🇩' },
  { iso: 'gp', dial: '+590', name: 'Guadeloupe', nameZh: '瓜德罗普', pinyin: 'gua de luo pu', flag: '🇬🇵' },
  { iso: 'gu', dial: '+1', name: 'Guam', nameZh: '关岛', pinyin: 'guan dao', flag: '🇬🇺' },
  { iso: 'gt', dial: '+502', name: 'Guatemala', nameZh: '危地马拉', pinyin: 'wei di ma la', flag: '🇬🇹' },
  { iso: 'gg', dial: '+44', name: 'Guernsey', nameZh: '根西岛', pinyin: 'gen xi dao', flag: '🇬🇬' },
  { iso: 'gn', dial: '+224', name: 'Guinea', nameZh: '几内亚', pinyin: 'ji nei ya', flag: '🇬🇳' },
  { iso: 'gw', dial: '+245', name: 'Guinea-Bissau', nameZh: '几内亚比绍', pinyin: 'ji nei ya bi shao', flag: '🇬🇼' },
  { iso: 'gy', dial: '+592', name: 'Guyana', nameZh: '圭亚那', pinyin: 'gui ya na', flag: '🇬🇾' },
  { iso: 'ht', dial: '+509', name: 'Haiti', nameZh: '海地', pinyin: 'hai di', flag: '🇭🇹' },
  { iso: 'hn', dial: '+504', name: 'Honduras', nameZh: '洪都拉斯', pinyin: 'hong dou la si', flag: '🇭🇳' },
  { iso: 'hk', dial: '+852', name: 'Hong Kong SAR China', nameZh: '中国香港特别行政区', pinyin: 'zhong guo xiang gang te bie xing zheng qu', flag: '🇭🇰' },
  { iso: 'hu', dial: '+36', name: 'Hungary', nameZh: '匈牙利', pinyin: 'xiong ya li', flag: '🇭🇺' },
  { iso: 'is', dial: '+354', name: 'Iceland', nameZh: '冰岛', pinyin: 'bing dao', flag: '🇮🇸' },
  { iso: 'in', dial: '+91', name: 'India', nameZh: '印度', pinyin: 'yin du', flag: '🇮🇳' },
  { iso: 'id', dial: '+62', name: 'Indonesia', nameZh: '印度尼西亚', pinyin: 'yin du ni xi ya', flag: '🇮🇩' },
  { iso: 'ir', dial: '+98', name: 'Iran', nameZh: '伊朗', pinyin: 'yi lang', flag: '🇮🇷' },
  { iso: 'iq', dial: '+964', name: 'Iraq', nameZh: '伊拉克', pinyin: 'yi la ke', flag: '🇮🇶' },
  { iso: 'ie', dial: '+353', name: 'Ireland', nameZh: '爱尔兰', pinyin: 'ai er lan', flag: '🇮🇪' },
  { iso: 'im', dial: '+44', name: 'Isle of Man', nameZh: '马恩岛', pinyin: 'ma en dao', flag: '🇮🇲' },
  { iso: 'il', dial: '+972', name: 'Israel', nameZh: '以色列', pinyin: 'yi se lie', flag: '🇮🇱' },
  { iso: 'it', dial: '+39', name: 'Italy', nameZh: '意大利', pinyin: 'yi da li', flag: '🇮🇹' },
  { iso: 'jm', dial: '+1', name: 'Jamaica', nameZh: '牙买加', pinyin: 'ya mai jia', flag: '🇯🇲' },
  { iso: 'jp', dial: '+81', name: 'Japan', nameZh: '日本', pinyin: 'ri ben', flag: '🇯🇵' },
  { iso: 'je', dial: '+44', name: 'Jersey', nameZh: '泽西岛', pinyin: 'ze xi dao', flag: '🇯🇪' },
  { iso: 'jo', dial: '+962', name: 'Jordan', nameZh: '约旦', pinyin: 'yue dan', flag: '🇯🇴' },
  { iso: 'kz', dial: '+7', name: 'Kazakhstan', nameZh: '哈萨克斯坦', pinyin: 'ha sa ke si tan', flag: '🇰🇿' },
  { iso: 'ke', dial: '+254', name: 'Kenya', nameZh: '肯尼亚', pinyin: 'ken ni ya', flag: '🇰🇪' },
  { iso: 'ki', dial: '+686', name: 'Kiribati', nameZh: '基里巴斯', pinyin: 'ji li ba si', flag: '🇰🇮' },
  { iso: 'xk', dial: '+383', name: 'Kosovo', nameZh: '科索沃', pinyin: 'ke suo wo', flag: '🇽🇰' },
  { iso: 'kw', dial: '+965', name: 'Kuwait', nameZh: '科威特', pinyin: 'ke wei te', flag: '🇰🇼' },
  { iso: 'kg', dial: '+996', name: 'Kyrgyzstan', nameZh: '吉尔吉斯斯坦', pinyin: 'ji er ji si si tan', flag: '🇰🇬' },
  { iso: 'la', dial: '+856', name: 'Laos', nameZh: '老挝', pinyin: 'lao wo', flag: '🇱🇦' },
  { iso: 'lv', dial: '+371', name: 'Latvia', nameZh: '拉脱维亚', pinyin: 'la tuo wei ya', flag: '🇱🇻' },
  { iso: 'lb', dial: '+961', name: 'Lebanon', nameZh: '黎巴嫩', pinyin: 'li ba nen', flag: '🇱🇧' },
  { iso: 'ls', dial: '+266', name: 'Lesotho', nameZh: '莱索托', pinyin: 'lai suo tuo', flag: '🇱🇸' },
  { iso: 'lr', dial: '+231', name: 'Liberia', nameZh: '利比里亚', pinyin: 'li bi li ya', flag: '🇱🇷' },
  { iso: 'ly', dial: '+218', name: 'Libya', nameZh: '利比亚', pinyin: 'li bi ya', flag: '🇱🇾' },
  { iso: 'li', dial: '+423', name: 'Liechtenstein', nameZh: '列支敦士登', pinyin: 'lie zhi dun shi deng', flag: '🇱🇮' },
  { iso: 'lt', dial: '+370', name: 'Lithuania', nameZh: '立陶宛', pinyin: 'li tao wan', flag: '🇱🇹' },
  { iso: 'lu', dial: '+352', name: 'Luxembourg', nameZh: '卢森堡', pinyin: 'lu sen bao', flag: '🇱🇺' },
  { iso: 'mo', dial: '+853', name: 'Macao SAR China', nameZh: '中国澳门特别行政区', pinyin: 'zhong guo ao men te bie xing zheng qu', flag: '🇲🇴' },
  { iso: 'mg', dial: '+261', name: 'Madagascar', nameZh: '马达加斯加', pinyin: 'ma da jia si jia', flag: '🇲🇬' },
  { iso: 'mw', dial: '+265', name: 'Malawi', nameZh: '马拉维', pinyin: 'ma la wei', flag: '🇲🇼' },
  { iso: 'my', dial: '+60', name: 'Malaysia', nameZh: '马来西亚', pinyin: 'ma lai xi ya', flag: '🇲🇾' },
  { iso: 'mv', dial: '+960', name: 'Maldives', nameZh: '马尔代夫', pinyin: 'ma er dai fu', flag: '🇲🇻' },
  { iso: 'ml', dial: '+223', name: 'Mali', nameZh: '马里', pinyin: 'ma li', flag: '🇲🇱' },
  { iso: 'mt', dial: '+356', name: 'Malta', nameZh: '马耳他', pinyin: 'ma er ta', flag: '🇲🇹' },
  { iso: 'mh', dial: '+692', name: 'Marshall Islands', nameZh: '马绍尔群岛', pinyin: 'ma shao er qun dao', flag: '🇲🇭' },
  { iso: 'mq', dial: '+596', name: 'Martinique', nameZh: '马提尼克', pinyin: 'ma ti ni ke', flag: '🇲🇶' },
  { iso: 'mr', dial: '+222', name: 'Mauritania', nameZh: '毛里塔尼亚', pinyin: 'mao li ta ni ya', flag: '🇲🇷' },
  { iso: 'mu', dial: '+230', name: 'Mauritius', nameZh: '毛里求斯', pinyin: 'mao li qiu si', flag: '🇲🇺' },
  { iso: 'yt', dial: '+262', name: 'Mayotte', nameZh: '马约特', pinyin: 'ma yue te', flag: '🇾🇹' },
  { iso: 'mx', dial: '+52', name: 'Mexico', nameZh: '墨西哥', pinyin: 'mo xi ge', flag: '🇲🇽' },
  { iso: 'fm', dial: '+691', name: 'Micronesia', nameZh: '密克罗尼西亚', pinyin: 'mi ke luo ni xi ya', flag: '🇫🇲' },
  { iso: 'md', dial: '+373', name: 'Moldova', nameZh: '摩尔多瓦', pinyin: 'mo er duo wa', flag: '🇲🇩' },
  { iso: 'mc', dial: '+377', name: 'Monaco', nameZh: '摩纳哥', pinyin: 'mo na ge', flag: '🇲🇨' },
  { iso: 'mn', dial: '+976', name: 'Mongolia', nameZh: '蒙古', pinyin: 'meng gu', flag: '🇲🇳' },
  { iso: 'me', dial: '+382', name: 'Montenegro', nameZh: '黑山', pinyin: 'hei shan', flag: '🇲🇪' },
  { iso: 'ms', dial: '+1', name: 'Montserrat', nameZh: '蒙特塞拉特', pinyin: 'meng te sai la te', flag: '🇲🇸' },
  { iso: 'ma', dial: '+212', name: 'Morocco', nameZh: '摩洛哥', pinyin: 'mo luo ge', flag: '🇲🇦' },
  { iso: 'mz', dial: '+258', name: 'Mozambique', nameZh: '莫桑比克', pinyin: 'mo sang bi ke', flag: '🇲🇿' },
  { iso: 'mm', dial: '+95', name: 'Myanmar (Burma)', nameZh: '缅甸', pinyin: 'mian dian', flag: '🇲🇲' },
  { iso: 'na', dial: '+264', name: 'Namibia', nameZh: '纳米比亚', pinyin: 'na mi bi ya', flag: '🇳🇦' },
  { iso: 'nr', dial: '+674', name: 'Nauru', nameZh: '瑙鲁', pinyin: 'nao lu', flag: '🇳🇷' },
  { iso: 'np', dial: '+977', name: 'Nepal', nameZh: '尼泊尔', pinyin: 'ni po er', flag: '🇳🇵' },
  { iso: 'nl', dial: '+31', name: 'Netherlands', nameZh: '荷兰', pinyin: 'he lan', flag: '🇳🇱' },
  { iso: 'nc', dial: '+687', name: 'New Caledonia', nameZh: '新喀里多尼亚', pinyin: 'xin ka li duo ni ya', flag: '🇳🇨' },
  { iso: 'nz', dial: '+64', name: 'New Zealand', nameZh: '新西兰', pinyin: 'xin xi lan', flag: '🇳🇿' },
  { iso: 'ni', dial: '+505', name: 'Nicaragua', nameZh: '尼加拉瓜', pinyin: 'ni jia la gua', flag: '🇳🇮' },
  { iso: 'ne', dial: '+227', name: 'Niger', nameZh: '尼日尔', pinyin: 'ni ri er', flag: '🇳🇪' },
  { iso: 'ng', dial: '+234', name: 'Nigeria', nameZh: '尼日利亚', pinyin: 'ni ri li ya', flag: '🇳🇬' },
  { iso: 'nu', dial: '+683', name: 'Niue', nameZh: '纽埃', pinyin: 'niu ai', flag: '🇳🇺' },
  { iso: 'nf', dial: '+672', name: 'Norfolk Island', nameZh: '诺福克岛', pinyin: 'nuo fu ke dao', flag: '🇳🇫' },
  { iso: 'kp', dial: '+850', name: 'North Korea', nameZh: '朝鲜', pinyin: 'chao xian', flag: '🇰🇵' },
  { iso: 'mk', dial: '+389', name: 'North Macedonia', nameZh: '北马其顿', pinyin: 'bei ma qi dun', flag: '🇲🇰' },
  { iso: 'mp', dial: '+1', name: 'Northern Mariana Islands', nameZh: '北马里亚纳群岛', pinyin: 'bei ma li ya na qun dao', flag: '🇲🇵' },
  { iso: 'no', dial: '+47', name: 'Norway', nameZh: '挪威', pinyin: 'nuo wei', flag: '🇳🇴' },
  { iso: 'om', dial: '+968', name: 'Oman', nameZh: '阿曼', pinyin: 'a man', flag: '🇴🇲' },
  { iso: 'pk', dial: '+92', name: 'Pakistan', nameZh: '巴基斯坦', pinyin: 'ba ji si tan', flag: '🇵🇰' },
  { iso: 'pw', dial: '+680', name: 'Palau', nameZh: '帕劳', pinyin: 'pa lao', flag: '🇵🇼' },
  { iso: 'ps', dial: '+970', name: 'Palestinian Territories', nameZh: '巴勒斯坦领土', pinyin: 'ba le si tan ling tu', flag: '🇵🇸' },
  { iso: 'pa', dial: '+507', name: 'Panama', nameZh: '巴拿马', pinyin: 'ba na ma', flag: '🇵🇦' },
  { iso: 'pg', dial: '+675', name: 'Papua New Guinea', nameZh: '巴布亚新几内亚', pinyin: 'ba bu ya xin ji nei ya', flag: '🇵🇬' },
  { iso: 'py', dial: '+595', name: 'Paraguay', nameZh: '巴拉圭', pinyin: 'ba la gui', flag: '🇵🇾' },
  { iso: 'pe', dial: '+51', name: 'Peru', nameZh: '秘鲁', pinyin: 'bi lu', flag: '🇵🇪' },
  { iso: 'ph', dial: '+63', name: 'Philippines', nameZh: '菲律宾', pinyin: 'fei lv bin', flag: '🇵🇭' },
  { iso: 'pl', dial: '+48', name: 'Poland', nameZh: '波兰', pinyin: 'bo lan', flag: '🇵🇱' },
  { iso: 'pt', dial: '+351', name: 'Portugal', nameZh: '葡萄牙', pinyin: 'pu tao ya', flag: '🇵🇹' },
  { iso: 'pr', dial: '+1', name: 'Puerto Rico', nameZh: '波多黎各', pinyin: 'bo duo li ge', flag: '🇵🇷' },
  { iso: 'qa', dial: '+974', name: 'Qatar', nameZh: '卡塔尔', pinyin: 'ka ta er', flag: '🇶🇦' },
  { iso: 're', dial: '+262', name: 'Réunion', nameZh: '留尼汪', pinyin: 'liu ni wang', flag: '🇷🇪' },
  { iso: 'ro', dial: '+40', name: 'Romania', nameZh: '罗马尼亚', pinyin: 'luo ma ni ya', flag: '🇷🇴' },
  { iso: 'ru', dial: '+7', name: 'Russia', nameZh: '俄罗斯', pinyin: 'e luo si', flag: '🇷🇺' },
  { iso: 'rw', dial: '+250', name: 'Rwanda', nameZh: '卢旺达', pinyin: 'lu wang da', flag: '🇷🇼' },
  { iso: 'ws', dial: '+685', name: 'Samoa', nameZh: '萨摩亚', pinyin: 'sa mo ya', flag: '🇼🇸' },
  { iso: 'sm', dial: '+378', name: 'San Marino', nameZh: '圣马力诺', pinyin: 'sheng ma li nuo', flag: '🇸🇲' },
  { iso: 'st', dial: '+239', name: 'São Tomé & Príncipe', nameZh: '圣多美和普林西比', pinyin: 'sheng duo mei he pu lin xi bi', flag: '🇸🇹' },
  { iso: 'sa', dial: '+966', name: 'Saudi Arabia', nameZh: '沙特阿拉伯', pinyin: 'sha te a la bo', flag: '🇸🇦' },
  { iso: 'sn', dial: '+221', name: 'Senegal', nameZh: '塞内加尔', pinyin: 'sai nei jia er', flag: '🇸🇳' },
  { iso: 'rs', dial: '+381', name: 'Serbia', nameZh: '塞尔维亚', pinyin: 'sai er wei ya', flag: '🇷🇸' },
  { iso: 'sc', dial: '+248', name: 'Seychelles', nameZh: '塞舌尔', pinyin: 'sai she er', flag: '🇸🇨' },
  { iso: 'sl', dial: '+232', name: 'Sierra Leone', nameZh: '塞拉利昂', pinyin: 'sai la li ang', flag: '🇸🇱' },
  { iso: 'sg', dial: '+65', name: 'Singapore', nameZh: '新加坡', pinyin: 'xin jia po', flag: '🇸🇬' },
  { iso: 'sx', dial: '+1', name: 'Sint Maarten', nameZh: '荷属圣马丁', pinyin: 'he shu sheng ma ding', flag: '🇸🇽' },
  { iso: 'sk', dial: '+421', name: 'Slovakia', nameZh: '斯洛伐克', pinyin: 'si luo fa ke', flag: '🇸🇰' },
  { iso: 'si', dial: '+386', name: 'Slovenia', nameZh: '斯洛文尼亚', pinyin: 'si luo wen ni ya', flag: '🇸🇮' },
  { iso: 'sb', dial: '+677', name: 'Solomon Islands', nameZh: '所罗门群岛', pinyin: 'suo luo men qun dao', flag: '🇸🇧' },
  { iso: 'so', dial: '+252', name: 'Somalia', nameZh: '索马里', pinyin: 'suo ma li', flag: '🇸🇴' },
  { iso: 'za', dial: '+27', name: 'South Africa', nameZh: '南非', pinyin: 'nan fei', flag: '🇿🇦' },
  { iso: 'kr', dial: '+82', name: 'South Korea', nameZh: '韩国', pinyin: 'han guo', flag: '🇰🇷' },
  { iso: 'ss', dial: '+211', name: 'South Sudan', nameZh: '南苏丹', pinyin: 'nan su dan', flag: '🇸🇸' },
  { iso: 'es', dial: '+34', name: 'Spain', nameZh: '西班牙', pinyin: 'xi ban ya', flag: '🇪🇸' },
  { iso: 'lk', dial: '+94', name: 'Sri Lanka', nameZh: '斯里兰卡', pinyin: 'si li lan ka', flag: '🇱🇰' },
  { iso: 'bl', dial: '+590', name: 'St. Barthélemy', nameZh: '圣巴泰勒米', pinyin: 'sheng ba tai lei mi', flag: '🇧🇱' },
  { iso: 'sh', dial: '+290', name: 'St. Helena', nameZh: '圣赫勒拿', pinyin: 'sheng he lei na', flag: '🇸🇭' },
  { iso: 'kn', dial: '+1', name: 'St. Kitts & Nevis', nameZh: '圣基茨和尼维斯', pinyin: 'sheng ji ci he ni wei si', flag: '🇰🇳' },
  { iso: 'lc', dial: '+1', name: 'St. Lucia', nameZh: '圣卢西亚', pinyin: 'sheng lu xi ya', flag: '🇱🇨' },
  { iso: 'mf', dial: '+590', name: 'St. Martin', nameZh: '法属圣马丁', pinyin: 'fa shu sheng ma ding', flag: '🇲🇫' },
  { iso: 'pm', dial: '+508', name: 'St. Pierre & Miquelon', nameZh: '圣皮埃尔和密克隆群岛', pinyin: 'sheng pi ai er he mi ke long qun dao', flag: '🇵🇲' },
  { iso: 'vc', dial: '+1', name: 'St. Vincent & Grenadines', nameZh: '圣文森特和格林纳丁斯', pinyin: 'sheng wen sen te he ge lin na ding si', flag: '🇻🇨' },
  { iso: 'sd', dial: '+249', name: 'Sudan', nameZh: '苏丹', pinyin: 'su dan', flag: '🇸🇩' },
  { iso: 'sr', dial: '+597', name: 'Suriname', nameZh: '苏里南', pinyin: 'su li nan', flag: '🇸🇷' },
  { iso: 'sj', dial: '+47', name: 'Svalbard & Jan Mayen', nameZh: '斯瓦尔巴和扬马延', pinyin: 'si wa er ba he yang ma yan', flag: '🇸🇯' },
  { iso: 'se', dial: '+46', name: 'Sweden', nameZh: '瑞典', pinyin: 'rui dian', flag: '🇸🇪' },
  { iso: 'ch', dial: '+41', name: 'Switzerland', nameZh: '瑞士', pinyin: 'rui shi', flag: '🇨🇭' },
  { iso: 'sy', dial: '+963', name: 'Syria', nameZh: '叙利亚', pinyin: 'xu li ya', flag: '🇸🇾' },
  { iso: 'tw', dial: '+886', name: 'Taiwan, China', nameZh: '中国台湾', pinyin: 'zhong guo tai wan', flag: '🇹🇼' },
  { iso: 'tj', dial: '+992', name: 'Tajikistan', nameZh: '塔吉克斯坦', pinyin: 'ta ji ke si tan', flag: '🇹🇯' },
  { iso: 'tz', dial: '+255', name: 'Tanzania', nameZh: '坦桑尼亚', pinyin: 'tan sang ni ya', flag: '🇹🇿' },
  { iso: 'th', dial: '+66', name: 'Thailand', nameZh: '泰国', pinyin: 'tai guo', flag: '🇹🇭' },
  { iso: 'tl', dial: '+670', name: 'Timor-Leste', nameZh: '东帝汶', pinyin: 'dong di wen', flag: '🇹🇱' },
  { iso: 'tg', dial: '+228', name: 'Togo', nameZh: '多哥', pinyin: 'duo ge', flag: '🇹🇬' },
  { iso: 'tk', dial: '+690', name: 'Tokelau', nameZh: '托克劳', pinyin: 'tuo ke lao', flag: '🇹🇰' },
  { iso: 'to', dial: '+676', name: 'Tonga', nameZh: '汤加', pinyin: 'tang jia', flag: '🇹🇴' },
  { iso: 'tt', dial: '+1', name: 'Trinidad & Tobago', nameZh: '特立尼达和多巴哥', pinyin: 'te li ni da he duo ba ge', flag: '🇹🇹' },
  { iso: 'tn', dial: '+216', name: 'Tunisia', nameZh: '突尼斯', pinyin: 'tu ni si', flag: '🇹🇳' },
  { iso: 'tr', dial: '+90', name: 'Turkey', nameZh: '土耳其', pinyin: 'tu er qi', flag: '🇹🇷' },
  { iso: 'tm', dial: '+993', name: 'Turkmenistan', nameZh: '土库曼斯坦', pinyin: 'tu ku man si tan', flag: '🇹🇲' },
  { iso: 'tc', dial: '+1', name: 'Turks & Caicos Islands', nameZh: '特克斯和凯科斯群岛', pinyin: 'te ke si he kai ke si qun dao', flag: '🇹🇨' },
  { iso: 'tv', dial: '+688', name: 'Tuvalu', nameZh: '图瓦卢', pinyin: 'tu wa lu', flag: '🇹🇻' },
  { iso: 'ug', dial: '+256', name: 'Uganda', nameZh: '乌干达', pinyin: 'wu gan da', flag: '🇺🇬' },
  { iso: 'ua', dial: '+380', name: 'Ukraine', nameZh: '乌克兰', pinyin: 'wu ke lan', flag: '🇺🇦' },
  { iso: 'ae', dial: '+971', name: 'United Arab Emirates', nameZh: '阿拉伯联合酋长国', pinyin: 'a la bo lian he qiu zhang guo', flag: '🇦🇪' },
  { iso: 'gb', dial: '+44', name: 'United Kingdom', nameZh: '英国', pinyin: 'ying guo', flag: '🇬🇧' },
  { iso: 'us', dial: '+1', name: 'United States', nameZh: '美国', pinyin: 'mei guo', flag: '🇺🇸' },
  { iso: 'uy', dial: '+598', name: 'Uruguay', nameZh: '乌拉圭', pinyin: 'wu la gui', flag: '🇺🇾' },
  { iso: 'vi', dial: '+1', name: 'U.S. Virgin Islands', nameZh: '美属维尔京群岛', pinyin: 'mei shu wei er jing qun dao', flag: '🇻🇮' },
  { iso: 'uz', dial: '+998', name: 'Uzbekistan', nameZh: '乌兹别克斯坦', pinyin: 'wu zi bie ke si tan', flag: '🇺🇿' },
  { iso: 'vu', dial: '+678', name: 'Vanuatu', nameZh: '瓦努阿图', pinyin: 'wa nu a tu', flag: '🇻🇺' },
  { iso: 'va', dial: '+39', name: 'Vatican City', nameZh: '梵蒂冈', pinyin: 'fan di gang', flag: '🇻🇦' },
  { iso: 've', dial: '+58', name: 'Venezuela', nameZh: '委内瑞拉', pinyin: 'wei nei rui la', flag: '🇻🇪' },
  { iso: 'vn', dial: '+84', name: 'Vietnam', nameZh: '越南', pinyin: 'yue nan', flag: '🇻🇳' },
  { iso: 'wf', dial: '+681', name: 'Wallis & Futuna', nameZh: '瓦利斯和富图纳', pinyin: 'wa li si he fu tu na', flag: '🇼🇫' },
  { iso: 'eh', dial: '+212', name: 'Western Sahara', nameZh: '西撒哈拉', pinyin: 'xi sa ha la', flag: '🇪🇭' },
  { iso: 'ye', dial: '+967', name: 'Yemen', nameZh: '也门', pinyin: 'ye men', flag: '🇾🇪' },
  { iso: 'zm', dial: '+260', name: 'Zambia', nameZh: '赞比亚', pinyin: 'zan bi ya', flag: '🇿🇲' },
  { iso: 'zw', dial: '+263', name: 'Zimbabwe', nameZh: '津巴布韦', pinyin: 'jin ba bu wei', flag: '🇿🇼' },
];

export type CountryCode = string;
export const DEFAULT_COUNTRY_CODE: CountryCode = "+86";